export const WEBSOCKET_MANAGER_RUNTIME_DEFAULTS = {
  eventDeduplicationCapacity: 100,
  eventDeduplicationTtlMs: 60000,
  keepAliveIntervalMs: 20000,
} as const;

export const WEBSOCKET_MANAGER_EVENT_DEDUPLICATION_CAPACITY =
  WEBSOCKET_MANAGER_RUNTIME_DEFAULTS.eventDeduplicationCapacity;
export const WEBSOCKET_MANAGER_EVENT_DEDUPLICATION_TTL_MS =
  WEBSOCKET_MANAGER_RUNTIME_DEFAULTS.eventDeduplicationTtlMs;
export const WEBSOCKET_MANAGER_KEEPALIVE_INTERVAL_MS =
  WEBSOCKET_MANAGER_RUNTIME_DEFAULTS.keepAliveIntervalMs;
