export const CONFIG_PIPELINE_SEPARATOR_LENGTH = 80;
export const CONFIG_PIPELINE_ANALYZER_WEIGHT_GROUP_PRECISION = 1;
export const CONFIG_PIPELINE_ANALYZER_PREVIEW_LIMIT = 5;
export const CONFIG_PIPELINE_ANALYZER_PREVIEW_WEIGHT_PRECISION = 2;
